# Workflow [ No indentation required for naming the workflow ]
name: hello

# On tells when the workflow should run [ Give Indentation by Tab ] 

on: 
  push:

# Job tells what the workflows should do, there can be one ore more jobs, hence we write jobs
# Jobs is an object so it needs indentation

jobs:
 # 1st job [ Give indentation]
  say-hello:
 # Creates an ephemeral (that lasts only for short time) conatiner with ubuntu running  
    runs-on: ubuntu-latest
  # that ephermal container will have steps to execute, hence name those steps and use run: run has the command

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Say hello to everyone
        run: echo "Hello Dosto"
   
      - name: current date
        run: echo "Current date and time is $(date)"
    
      - name: Print the current branch
        run: echo running on branch ${GITHUB_REF##*/}
  
      - name: List files in the repository
        run: ls -al

      - name: Print OS name 
        run: echo "$RUNNER_OS"