# # Goal Uses a matrix strategy to run the same job across:
# Python versions: 3.10, 3.11, 3.12
# Each job installs Python and prints the version
# Watch all 3 run in parallel

name: Matrix-strategy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python version
        run: python --version
