# # Goal Go to your repo → Settings → Secrets and Variables → Actions
# Create a secret called MY_SECRET_MESSAGE
# Create a workflow that reads it and prints: The secret is set: true (never print the actual value)
# Try to print ${{ secrets.MY_SECRET_MESSAGE }} directly — what does GitHub show?


name: Secret Variables

on:
  push:

jobs:
  secret-variable:
    runs-on: ubuntu-latest

    steps:
     - name: Print the secret
       run: echo "The secret is set:true"